# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Facebook' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'FacebookCore'
  pod 'FacebookLogin'
  # Pods for Facebook

  target 'FacebookTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FacebookUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
